'use client';

import { useState } from 'react';
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query';
import { apiFetch, getErrorMessage } from '@/lib/client/api';
import { profileUpdateSchema, addressSchema, type Address } from '@/contracts/shopwave.schema';
import { useAuth } from '@/context/AuthContext';

export function ProfileForm() {
  const { user } = useAuth(); const queryClient = useQueryClient();
  const [firstName, setFirstName] = useState<string | null>(null); const [lastName, setLastName] = useState<string | null>(null); const [mobile, setMobile] = useState<string | null>(null); const [message, setMessage] = useState<string | null>(null);
  const addresses = useQuery<Address[]>({ queryKey: ['addresses', user?.id], queryFn: async () => { const data = await apiFetch<unknown>('/api/store/me/addresses'); if (!Array.isArray(data)) throw new Error('Respuesta inválida'); return data.flatMap((item, index) => { const parsed = addressSchema.safeParse(item); return parsed.success ? [{ ...parsed.data, id: String(index) }] : []; }); }, enabled: Boolean(user) });
  const update = useMutation({ mutationFn: (input: { firstName: string; lastName: string; mobile: string }) => apiFetch('/api/store/me', { method: 'PATCH', body: JSON.stringify(input) }), onSuccess: (data) => { queryClient.setQueryData(['session'], (current: { user?: unknown } | undefined) => current ? { ...current, user: data } : current); setMessage('Perfil actualizado.'); } });
  const currentFirstName = firstName ?? user?.firstName ?? ''; const currentLastName = lastName ?? user?.lastName ?? ''; const currentMobile = mobile ?? user?.mobile ?? '';
  const submit = (event: React.FormEvent) => { event.preventDefault(); const parsed = profileUpdateSchema.safeParse({ firstName: currentFirstName, lastName: currentLastName, mobile: currentMobile }); if (!parsed.success) { setMessage(parsed.error.issues[0]?.message ?? 'Revisa los datos'); return; } setMessage(null); update.mutate(parsed.data); };
  return <div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="card p-6"><div><p className="eyebrow">Datos personales</p><h2 className="mt-2 text-2xl font-semibold">Tu perfil</h2></div><form onSubmit={submit} className="mt-7 space-y-4"><label className="block text-sm font-semibold">Correo electrónico<input className="field bg-panel text-muted" value={user?.email ?? ''} readOnly /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold">Nombre<input className="field" value={currentFirstName} onChange={(e) => setFirstName(e.target.value)} /></label><label className="block text-sm font-semibold">Apellido<input className="field" value={currentLastName} onChange={(e) => setLastName(e.target.value)} /></label></div><label className="block text-sm font-semibold">Celular<input className="field" value={currentMobile} onChange={(e) => setMobile(e.target.value)} /></label><button type="submit" disabled={update.isPending} className="button button-primary">{update.isPending ? 'Guardando…' : 'Guardar cambios'}</button>{message && <p className={`text-sm ${message.includes('actualizado') ? 'text-success' : 'text-danger'}`} role="status">{message}</p>}{update.error && <p className="text-sm text-danger" role="alert">{getErrorMessage(update.error)}</p>}</form></section><section className="card p-6"><p className="eyebrow">Solo lectura</p><h2 className="mt-2 text-2xl font-semibold">Direcciones guardadas</h2>{addresses.isLoading ? <p className="mt-6 text-sm text-muted">Cargando direcciones…</p> : addresses.error ? <p className="mt-6 text-sm text-danger" role="alert">No pudimos cargar tus direcciones.</p> : addresses.data?.length ? <ul className="mt-6 space-y-3">{addresses.data.map((address) => <li key={address.id} className="rounded-xl border border-line p-4 text-sm"><p className="font-semibold">{address.firstName} {address.lastName}</p><p className="mt-1 text-muted">{address.streetAddress}, {address.city}</p><p className="text-muted">{address.department} · {address.mobile}</p></li>)}</ul> : <div className="mt-6 rounded-xl bg-brand-soft p-4 text-sm text-brand-strong">Todavía no tienes direcciones guardadas. Podrás guardar una durante el checkout.</div>}</section></div>;
}
