import Link from 'next/link';
import { ArrowRight, CheckCircle2, ShieldCheck, Sparkles, Truck } from 'lucide-react';
import { getCatalog } from '@/lib/server/catalog';
import { ProductGrid } from '@/components/products/ProductGrid';

export const dynamic = 'force-dynamic';

export default async function HomePage() {
  const featured = await getCatalog({ page: '0', size: '8', sort: 'discount_desc' });
  return <>
    <section className="mx-auto grid max-w-7xl gap-10 px-4 pb-16 pt-14 sm:px-6 lg:grid-cols-[1.05fr_.95fr] lg:items-center lg:px-8 lg:pb-24 lg:pt-20">
      <div><p className="eyebrow flex items-center gap-2"><Sparkles size={15} />Selección local · Bolivia</p><h1 className="mt-5 max-w-2xl text-5xl font-semibold leading-[1.05] tracking-[-0.05em] text-ink sm:text-6xl lg:text-7xl">Compra menos al azar. <span className="text-brand">Elige mejor.</span></h1><p className="mt-6 max-w-xl text-lg leading-8 text-muted">Un catálogo curado, precios claros y una experiencia de compra construida para que encuentres lo que buscas sin ruido.</p><div className="mt-8 flex flex-wrap gap-3"><Link href="/products" className="button button-primary">Explorar catálogo <ArrowRight size={17} /></Link><Link href="#featured" className="button button-secondary">Ver destacados</Link></div><div className="mt-10 flex flex-wrap gap-x-6 gap-y-3 text-sm text-muted"><span className="flex items-center gap-2"><CheckCircle2 size={16} className="text-success" />Stock por variante</span><span className="flex items-center gap-2"><ShieldCheck size={16} className="text-success" />Pago simulado seguro</span></div></div>
      <div className="relative overflow-hidden rounded-[2rem] bg-[#24153d] p-6 text-white shadow-[0_24px_80px_rgba(61,24,111,.25)] sm:p-10"><div className="absolute -right-16 -top-16 size-64 rounded-full bg-[#8f63e8]/35 blur-2xl" /><div className="absolute -bottom-20 -left-12 size-56 rounded-full bg-[#f5bd72]/20 blur-2xl" /><div className="relative flex min-h-[360px] flex-col justify-between"><div className="flex items-center justify-between"><span className="rounded-full border border-white/20 px-3 py-1 text-xs font-semibold uppercase tracking-wider text-white/70">Nueva temporada</span><span className="text-sm text-white/60">01 / 04</span></div><div><p className="text-sm text-white/60">Lo esencial, bien elegido</p><p className="mt-3 max-w-sm text-4xl font-semibold leading-tight tracking-tight">Diseño que acompaña tu ritmo.</p><div className="mt-8 flex items-center gap-3 text-sm text-white/70"><span className="grid size-10 place-items-center rounded-full bg-white/10"><Truck size={18} /></span>Envíos y atención pensados para tu día a día.</div></div></div></div>
    </section>
    <section id="featured" className="mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8"><div className="mb-7 flex items-end justify-between gap-4"><div><p className="eyebrow">Para descubrir</p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Favoritos de la comunidad</h2></div><Link href="/products" className="hidden items-center gap-1 text-sm font-semibold text-brand hover:text-brand-strong sm:flex">Ver todo <ArrowRight size={16} /></Link></div><ProductGrid products={featured?.items ?? []} /></section>
    <section className="mx-auto grid max-w-7xl gap-4 px-4 py-8 sm:grid-cols-3 sm:px-6 lg:px-8"><div className="card p-5"><CheckCircle2 className="text-brand" size={21} /><h3 className="mt-4 font-semibold">Información honesta</h3><p className="mt-2 text-sm leading-6 text-muted">Precios en BOB y disponibilidad por variante, sin sorpresas al final.</p></div><div className="card p-5"><ShieldCheck className="text-brand" size={21} /><h3 className="mt-4 font-semibold">Pago simulado</h3><p className="mt-2 text-sm leading-6 text-muted">Este portfolio no solicita ni almacena números de tarjeta reales.</p></div><div className="card p-5"><Truck className="text-brand" size={21} /><h3 className="mt-4 font-semibold">Compra trazable</h3><p className="mt-2 text-sm leading-6 text-muted">Consulta el estado y detalle de cada pedido desde tu cuenta.</p></div></section>
  </>;
}
